# Generated by Django 4.1 on 2022-09-09 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_followerscount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FollowersCount',
        ),
    ]
