# Generated by Django 4.1 on 2022-09-09 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_profile_followers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='followers',
        ),
        migrations.DeleteModel(
            name='FollowersCount',
        ),
    ]
